#this is context properties
#Fri Jun 24 12:02:38 CEST 2022
db_in_AdditionalParams=noDatetimeStringSync\=true&enabledTLSProtocols\=TLSv1.2,TLSv1.1,TLSv1
db_in_Password=enc\:routine.encryption.key.v1\:PTDJOK4CvRWgKTQ6BhXP06sSAwgH7vm98D90qlj7mKz7pMel
db_in_Server=192.168.1.33
db_in_Port=5216
db_in_Login=talend
db_in_Database=db_in
db_out_Password=enc\:routine.encryption.key.v1\:4c2pcKbr0/H7j2N0sOTlOcLaeW2yunYujal6AVRf8RszJQ0U
db_out_Port=3306
db_out_Database=db_out
db_out_Server=localhost
db_out_Login=root
db_out_AdditionalParams=noDatetimeStringSync\=true&enabledTLSProtocols\=TLSv1.2,TLSv1.1,TLSv1
