#this is context properties
#Fri Jun 24 12:02:34 CEST 2022
db_in_AdditionalParams=noDatetimeStringSync\=true&enabledTLSProtocols\=TLSv1.2,TLSv1.1,TLSv1
db_in_Password=enc\:routine.encryption.key.v1\:F4fxuYReknCXfK+OiyRa3iKYdxwl/9kOO7E/YZLAxL3q+ARq
db_in_Server=192.168.1.33
db_in_Port=5216
db_in_Login=talend
db_in_Database=db_in
db_out_Password=enc\:routine.encryption.key.v1\:4y569mop8yWGjdDZ/FQ9dF0UiPt6TaAEDMv4zNnsseT3N63h
db_out_Port=3306
db_out_Database=db_out
db_out_Server=localhost
db_out_Login=root
db_out_AdditionalParams=noDatetimeStringSync\=true&enabledTLSProtocols\=TLSv1.2,TLSv1.1,TLSv1
