#this is context properties
#Wed Jun 22 16:32:16 CEST 2022
db_out_Port=3306
db_out_Database=db_out
db_out_Login=root
db_out_AdditionalParams=noDatetimeStringSync\=true&enabledTLSProtocols\=TLSv1.2,TLSv1.1,TLSv1
db_out_Server=localhost
db_out_Password=enc\:routine.encryption.key.v1\:qPXrtgjBJHKDInJZ9M8KtGgyeCVwB5Jj0NaLZzM7BfdaQdDP
db_in_Login=root
db_in_AdditionalParams=noDatetimeStringSync\=true&enabledTLSProtocols\=TLSv1.2,TLSv1.1,TLSv1
db_in_Server=localhost
db_in_Password=enc\:routine.encryption.key.v1\:gAJ8149a9B9JiPQrllk7mzlJVTpDySkA81NFapuvOGT1gj9q
db_in_Database=db_in
db_in_Port=3306
data_dir=C\:/talend/data_dir/
