#this is context properties
#Fri Jun 24 12:02:37 CEST 2022
db_in_AdditionalParams=noDatetimeStringSync\=true&enabledTLSProtocols\=TLSv1.2,TLSv1.1,TLSv1
db_in_Password=enc\:routine.encryption.key.v1\:svaI1t0oOzYkSzFBctYoSGFsUaIgCx7xPW7gJA78+AWAcCZ4
db_in_Server=localhost
db_in_Port=3306
db_in_Login=root
db_in_Database=db_in
db_out_Password=enc\:routine.encryption.key.v1\:h/xJS1LGhTV2S1PVluNN2fmN44AgV7XqeTXKB9BgDMZ7M7lc
db_out_Port=3306
db_out_Database=db_out
db_out_Server=localhost
db_out_Login=root
db_out_AdditionalParams=noDatetimeStringSync\=true&enabledTLSProtocols\=TLSv1.2,TLSv1.1,TLSv1
