#this is context properties
#Fri Jun 24 12:02:38 CEST 2022
db_in_AdditionalParams=noDatetimeStringSync\=true&enabledTLSProtocols\=TLSv1.2,TLSv1.1,TLSv1
db_in_Password=enc\:routine.encryption.key.v1\:i5zgFUEJVJ9lmMsa0lTxODpnAPJ03KDZkPi5usjF7FFDlSg9
db_in_Server=localhost
db_in_Port=3306
db_in_Login=root
db_in_Database=db_in
db_out_Password=enc\:routine.encryption.key.v1\:Nwv0Ws5bFuNokjNI7LSCX+g4bXJ029YPLxrFG0FOyYwm1NNo
db_out_Port=3306
db_out_Database=db_out
db_out_Server=localhost
db_out_Login=root
db_out_AdditionalParams=noDatetimeStringSync\=true&enabledTLSProtocols\=TLSv1.2,TLSv1.1,TLSv1
