#this is context properties
#Tue Jun 21 11:00:43 CEST 2022
db_in_AdditionalParams=noDatetimeStringSync\=true&enabledTLSProtocols\=TLSv1.2,TLSv1.1,TLSv1
db_in_Database=db_in
db_in_Login=root
db_in_Password=enc\:routine.encryption.key.v1\:UaKZOJplE3HzGucZcZoIFnTtzFt4k662z5IHTSpL9qgZ6EsC
db_in_Port=3306
db_in_Server=localhost
data_dir=C\:/talend/data_dir/
