#this is context properties
#Tue Jun 21 11:00:43 CEST 2022
data_dir=/home/talend/
db_in_AdditionalParams=noDatetimeStringSync\=true&enabledTLSProtocols\=TLSv1.2,TLSv1.1,TLSv1
db_in_Password=enc\:routine.encryption.key.v1\:OB6fOQZ8QycKvmkF54cjJe9axiJ3yTYYFEQjkFw+xruJgUTM
db_in_Server=192.168.1.33
db_in_Port=5216
db_in_Login=talend
db_in_Database=db_in
