#this is context properties
#Wed Jun 22 09:18:21 CEST 2022
db_in_AdditionalParams=noDatetimeStringSync\=true&enabledTLSProtocols\=TLSv1.2,TLSv1.1,TLSv1
db_in_Password=enc\:routine.encryption.key.v1\:GHQXhtcl81qbOTAK021oTOCe/VDW6lfcsE56GgNPd8hxbUP3
db_in_Server=localhost
db_in_Port=3306
db_in_Login=root
db_in_Database=db_in
data_dir=C\:/talend/data_dir/
