#this is context properties
#Wed Jun 22 09:18:21 CEST 2022
db_in_AdditionalParams=noDatetimeStringSync\=true&enabledTLSProtocols\=TLSv1.2,TLSv1.1,TLSv1
db_in_Password=enc\:routine.encryption.key.v1\:N5i4VXbQ1YextmaFmYMtvNrJFdc+NKPZmI8b+XtkH51mrBLt
db_in_Server=192.168.1.33
db_in_Port=5216
db_in_Login=talend
db_in_Database=db_in
data_dir=/home/talend/
