#this is context properties
#Wed Jun 22 16:32:15 CEST 2022
db_in_AdditionalParams=noDatetimeStringSync\=true&enabledTLSProtocols\=TLSv1.2,TLSv1.1,TLSv1
db_in_Password=enc\:routine.encryption.key.v1\:LvRBszqlBwWdv8roK/Fdclth9zy2Ll3D4B2iaZVpOVX+A+GB
db_in_Server=localhost
db_in_Port=3306
db_in_Login=root
db_in_Database=db_in
db_out_Password=enc\:routine.encryption.key.v1\:5zxEouKwfRMoCFn6i+5QPZtRaeNerx/eg860SFxsMvDQTXNj
db_out_Port=3306
db_out_Database=db_out
db_out_Server=localhost
db_out_Login=root
db_out_AdditionalParams=noDatetimeStringSync\=true&enabledTLSProtocols\=TLSv1.2,TLSv1.1,TLSv1
