#this is context properties
#Fri Jun 24 16:53:39 CEST 2022
db_out_AdditionalParams=noDatetimeStringSync\=true&enabledTLSProtocols\=TLSv1.2,TLSv1.1,TLSv1
db_out_Database=db_out
db_out_Login=root
db_out_Password=enc\:routine.encryption.key.v1\:GkwL6crtHxsIyIo5o1yEVjVzXWuKJlOogu8JOAOuNdHJhBHg
db_out_Port=3306
db_out_Server=localhost
api_url=https\://gorest.co.in/public/v2/
data_dir=C\:/talend/data_dir/
nb_cpus=6
