#this is context properties
#Fri Jun 24 16:53:39 CEST 2022
db_out_AdditionalParams=noDatetimeStringSync\=true&enabledTLSProtocols\=TLSv1.2,TLSv1.1,TLSv1
db_out_Database=db_out
db_out_Login=root
db_out_Password=enc\:routine.encryption.key.v1\:WZOlG80hd4XeSaiDASlh99ncRNDyUkQZUDzRKjY9M3SmTul4
db_out_Port=3306
db_out_Server=localhost
api_url=
data_dir=/home/talend/
nb_cpus=
