#this is context properties
#Wed Jun 22 16:32:16 CEST 2022
db_out_Port=3306
db_out_Database=db_out
db_out_Login=root
db_out_AdditionalParams=noDatetimeStringSync\=true&enabledTLSProtocols\=TLSv1.2,TLSv1.1,TLSv1
db_out_Server=localhost
db_out_Password=enc\:routine.encryption.key.v1\:42bBtVJynKt0z956lxoJoi7zGW82gcLINP78GFQj+ReAUY6P
db_in_Login=talend
db_in_AdditionalParams=noDatetimeStringSync\=true&enabledTLSProtocols\=TLSv1.2,TLSv1.1,TLSv1
db_in_Server=192.168.1.33
db_in_Password=enc\:routine.encryption.key.v1\:8WnH7TckS+IoIJWD+k32l+PUKNFO+OL2gkFwI4EJ5VuWZ5jN
db_in_Database=db_in
db_in_Port=5216
data_dir=/home/talend/
