#this is context properties
#Wed Jun 22 16:32:16 CEST 2022
db_in_AdditionalParams=noDatetimeStringSync\=true&enabledTLSProtocols\=TLSv1.2,TLSv1.1,TLSv1
db_in_Password=enc\:routine.encryption.key.v1\:J/FfRd4GJt323IhRAhTwk+3Buup1edIagrzTX+CrQSCvc3Tk
db_in_Server=localhost
db_in_Port=3306
db_in_Login=root
db_in_Database=db_in
db_out_Password=enc\:routine.encryption.key.v1\:ixVo/eTZtMD8n9HjveU6bw0uwEMe2Q0+s46QXmgTLgSRo7Jh
db_out_Port=3306
db_out_Database=db_out
db_out_Server=localhost
db_out_Login=root
db_out_AdditionalParams=noDatetimeStringSync\=true&enabledTLSProtocols\=TLSv1.2,TLSv1.1,TLSv1
