#this is context properties
#Wed Jun 22 16:32:16 CEST 2022
db_in_AdditionalParams=noDatetimeStringSync\=true&enabledTLSProtocols\=TLSv1.2,TLSv1.1,TLSv1
db_in_Password=enc\:routine.encryption.key.v1\:Hn06e5VyVj4gGLmMTjyFSi4PvmbqkzAo4BzqAbCVOW6hVj9e
db_in_Server=192.168.1.33
db_in_Port=5216
db_in_Login=talend
db_in_Database=db_in
db_out_Password=enc\:routine.encryption.key.v1\:H2kGuXMLQoRcBN2jWM4E2K/3TtfOCZsRJxbBCSjNNaqc2mm7
db_out_Port=3306
db_out_Database=db_out
db_out_Server=localhost
db_out_Login=root
db_out_AdditionalParams=noDatetimeStringSync\=true&enabledTLSProtocols\=TLSv1.2,TLSv1.1,TLSv1
