#this is context properties
#Wed Jun 22 16:32:15 CEST 2022
db_in_AdditionalParams=noDatetimeStringSync\=true&enabledTLSProtocols\=TLSv1.2,TLSv1.1,TLSv1
db_in_Password=enc\:routine.encryption.key.v1\:EB1/BM0APq5IYchIolyzpRI5/62Zx7Z7sFLzhTXL+EC0xAdw
db_in_Server=192.168.1.33
db_in_Port=5216
db_in_Login=talend
db_in_Database=db_in
db_out_Password=enc\:routine.encryption.key.v1\:gYUOiebAweBMVTfxcRNTA9Cu4kbGUGOSx+p3KNPjN3YuUNZ/
db_out_Port=3306
db_out_Database=db_out
db_out_Server=localhost
db_out_Login=root
db_out_AdditionalParams=noDatetimeStringSync\=true&enabledTLSProtocols\=TLSv1.2,TLSv1.1,TLSv1
